[options]
; --- Безопасность ---
; master password для управления базами через веб
admin_passwd = S7r0ng

; --- База данных ---
db_host = localhost
db_port = 5432
db_user = admin
db_password = admin

; --- Пути ---
; Укажи все каталоги с модулями через запятую
addons_path = /home/mikita/project/odoo/odoo/addons,/home/mikita/project/odoo/odoo/custom_addons
data_dir = /home/mikita/project/odoo/odoo/.odoo_data



; --- Оптимизация ---
workers = 4
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648


; --- WebSocket / Longpolling ---
longpolling_port = 8072